### PR TITLE
Advanced settings: Add wired LAN static IP support

### LINKED ISSUE #243: [Feature Request] Add static IPs and file uploading for public key file
Those are the two main features, i wish they were around in rpi-imager.
And maybe a button for advanced settings.

### PR DESCRIPTION
**Pull request by simonkeyd**
This commit enables users to configure a static IP and DNS servers to wired eth0 interface.

This is done by changing popup UI to allow one to specify IP, gateway and DNS servers. And also by adding first run and cloud-init part to configure /etc/dhcpcd.conf accordingly. Finally by ensuring that new settings are also saved.

fixes #243 #288

### CODE REVIEW

**Comment by simonkeyd** [comment]
bump @maxnet @lurch

**Comment by JinShil** [comment]
What about Network Manager?

**Comment by maxnet** [comment]
Not sure if static network configuration is a safe enough feature to include, given the number of less technical users using Imager.
Can disrupt other stuff in network if wrongly configured to use an IP already in use by something else.

Think setting a .local hostname is good enough for most users to reach their Pi, and does not come with risks.

**Comment by XECDesign** [comment]
Any such changes would need to be supported by these scripts first:

https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/usr/lib/raspberrypi-sys-mods/imager_custom
https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/usr/lib/raspberrypi-sys-mods/init_config

So I think the workflow here should be:

1) Open an issue over at raspberrypi-sys-mods' issue tracker to check whether this feature would be added

1) If so, send a PR there, supporting dhcpcd and NetworkManager (which we plan to move to)

1) If accepted, send a PR here

**Comment by tdewey-rpi** [comment]
We're coming up on the 1 year anniversary since the last comment on this PR.

I'm minded not to accept this change.

I concur with @maxnet that an Avahi advertisement is probably the safest mechanism - the risk of collisions, etc with static IPs is something that requires technical expertise to diagnose and solve - and if a user has those skills, they are probably capable of using either mDNS discovery to identify their Raspberry Pi, or using their router to set a static DHCP lease.

Let me know if you feel I'm incorrect in my assessment before November 9th, otherwise I'll close this PR.

**Comment by lurch** [comment]
There's a bunch of documentation around finding your Pi's IP address at https://www.raspberrypi.com/documentation/computers/remote-access.html#ip-address
And see also https://www.raspberrypi.com/documentation/computers/configuration.html#assign-a-static-ip-address

**Comment by tdewey-rpi** [comment]
Closing, as deadline for comments has long passed.

**Pull request closed without merging**
