### PR TITLE
meta: v1.8.3

### PR DESCRIPTION
**Pull request by tdewey-rpi**
Fixes typo in previous changelog item, bumps the version to cover "no filtering" fix.

### CODE REVIEW

**Comment by tdewey-rpi** [comment]
Hold this one, we have an urgent hotfix coming in.

**Comment by tdewey-rpi** [comment]
Safe to merge.

**Comment by tdewey-rpi** [comment]
@cillian64 @maxnet Once this merges, please cut a release for the usual desktop platforms and put it into Raspberry Pi OS' package repo.

**Review by cillian64 — APPROVED** [review]
lgtm

**Pull request merged**
