### PR TITLE
OSX: update the icon to follow the Human Interface Guidelines

### LINKED ISSUE #397: Update macOS Icon to Big Sur Style
Since the release of macOS Big Sur back in 2020, Apple has redesigned many of their app's icons to use a rounded square design, and many third-party apps have followed suit.

The Raspberry Pi Imager currently looks out of place amongst other apps that have already adopted this style. 

Apple has provided resources for this new style in their [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

### PR DESCRIPTION
**Pull request by rsre**
Closes #397 

Updates the macOS icon file to match the current style proposed by Apple.

The updated icon matches nicely with the rest of the applications in the system.

Updated Raspberry Pi Imager icon matching Big Sur style

### CODE REVIEW

**Comment by tdewey-rpi** [comment]
@jackbenwillis What's your take on this?

**Comment by tdewey-rpi** [comment]
We'll roll this icon update into 1.8.2.

**Comment by tdewey-rpi** [comment]
We've merged an equivalent change, and this should hopefully address your concerns, @rsre. Let me know if it doesn't work for you.

**Comment by rsre** [comment]
Sure, thanks for taking care @tdewey-rpi!

**Pull request closed without merging**
