### PR TITLE
Add option to run script after writing image

### PR DESCRIPTION
**Pull request by andrewmarklloyd**
I'm not a C++ programmer but I'm taking a shot at adding an option to run an arbitrary script after the image write has finished. I had the same use case as mentioned in https://github.com/raspberrypi/rpi-imager/issues/193

### CODE REVIEW

**Comment by maxnet** [comment]
Please do not use pull requests for "draft submissions" that only print "button clicked" to console.

**Comment by andrewmarklloyd** [comment]
My apologies but my plan was to keep it in a draft state but keep pushing changes until the feature was complete, then submit for review. This allows people interested to follow the changes during implementation. Sounds like this isn’t preferred though so I will wait to submit the PR until the feature is ready.

**Comment by lurch** [comment]
Probably more appropriate to post a comment on #193 saying something like "I've started working on this at xxxxxx, any feedback or comments welcome" ?

**Comment by maxnet** [comment]
>My apologies but my plan was to keep it in a draft state but keep pushing changes until the feature was complete, 

Just keep in mind that for every push you make the 32 people subscribed to this repository get an e-mail notification.

And I cannot guarantee your code will be accepted when you do are done.
(Regardless if we should have this feature or not).

**Comment by andrewmarklloyd** [comment]
@maxnet thank you for the feedback, I hadn't considered that I would be spamming notifications when pushing commits. You have valid concerns in #193 so it doesn't sound like this feature should be implemented. @lurch that's a good recommendation to comment a link to the feature work in the issue.

In the future I might recommend making first time contributors [feel welcome](https://opensource.guide/building-community/#make-people-feel-welcome). I also believe adding a [CONTRIBUTING.md](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines) file will help prevent workflow expectation conflicts like this in the future.

Thanks for maintaining a great piece of software supporting the Raspberry Pi!

**Pull request closed without merging**
