### PR TITLE
Allow relative URLs in the repository files

### PR DESCRIPTION
**Pull request by jvprat**
This adds support for using relative URLs in the `icon`, `url` and `subitems_url` fields of the repository files. If the URL in one of these fields is relative, it's preprocessed into an absolute one by using the URL of the containing JSON file as its base. This eases the relocation of repository files without having to change their contents (for example, I could create and test a repository in my local filesystem and then upload them without having to change anything).

### CODE REVIEW

**Comment by maxnet** [comment]
Do would provide backwards compatibility issues if distributions to which we link to using the subitem_urls mechanism start using relative URLs.
rpi-imager does not provide any self-update mechanism, so end-users may still be running older versions that only accept absolute URLs.

**Comment by sp-jordi-vilalta** [comment]
In that case maybe it's a good time to introduce an `oslist_format_version` field at the file root so the imager can warn the user that a newer version should be used

**Comment by jvprat** [comment]
In that case maybe it's a good time to introduce an `oslist_format_version` field at the file root so the imager can warn the user that a newer version should be used

**Comment by maxnet** [comment]
>In that case maybe it's a good time to introduce an oslist_format_version field at the file root so the imager can warn the user 
>that a newer version should be used

But is support for relatively URLs -something that only provides some additional convenience to developers and not to end-users-, something end-users should be forced to upgrade their Imager for?

**Comment by tdewey-rpi** [comment]
Closing this - it's long stale now, with multiple conflicts.

**Pull request closed without merging**
