### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@maxnet 

Please check and merge. Thanks.

### CODE REVIEW

**Comment by bovirus** [comment]
@maxnet 

Please rebuild program including update of Italian/German/Chinese/Slovak language. Thanks.

**Comment by maxnet** [comment]
>Please rebuild program including update of Italian/German/Chinese/Slovak language. Thanks.

The build in the "advanced options problems" issue has the new translations: https://github.com/raspberrypi/rpi-imager/issues/171

**Comment by bovirus** [comment]
OK: I'm taling about 1.7 beta.
And include alla latest langauges updated (IT(CN/DE/SL)?

**Comment by maxnet** [comment]
Build should have everything that was merged into git. (up to and including 2bbb8bfba78b2b86d0d6c6809ea43410686540c8)

**Pull request merged**
