### PR TITLE
Add i18n feature

### PR DESCRIPTION
**Pull request by YuzukiTsuru**
use a simple header file to achieve i18n feature.
the i18n translates file is in `i18n`

- change in qml file
```
== -> ===
!=  -> !==
```

### CODE REVIEW

**Comment by ghollingworth** [comment]
@spl237 Is there a way of providing language choice without having the ugly selection box in the middle of the screen?  Can we get language selection from the installation instead?

**Comment by spl237** [comment]
Depends on the system you are running on; can't say for Windows or Mac, but on Linux you should be able to read the system locale; it's in an environment variable. I'd assume Windows and Mac have similar mechanisms, but don't know what they are.

**Comment by ghollingworth** [comment]
I assume that Qt has a default locale based on the system locale?  So maybe it's just a case of using that?

**Comment by spl237** [comment]
https://doc.qt.io/qt-5/qml-qtqml-locale.html may be relevant....

**Comment by maxnet** [comment]
Cherry picked your .ts

**Pull request closed without merging**
