### PR TITLE
Update rpi logo and its alignment/positioning

### PR DESCRIPTION
**Pull request by cillian64**
- Change logo back to colour logo
- Change logo alignment and positioning to make it generally left-aligned, have some nice padding above and below it, and to not occupy the full window width.

### CODE REVIEW

**Comment by cillian64** [comment]
image
image

**Comment by lurch** [comment]
ping also @jackbenwillis

**Comment by tdewey-rpi** [comment]
Jack, I believe this aligns with your position & scale request, but I'd prefer if you could leave a comment stating you're happy/unhappy.

**Comment by jackbenwillis** [comment]
Very happy. Thanks!

**Review by tdewey-rpi — APPROVED** [review]

**Pull request merged**
