### PR TITLE
Add Korean patch

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
* Add `rpi-imager_ko.ts`
* Update  in `translations.qrc`
```
<file>rpi-imager_ko.qm</file>
```

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
If the original is more meaningful than the translation, the original is maintained.

**Comment by RuffaloLavoisier** [comment]
@maxnet 
Hello, Thank you for merge !
but i wonder why did you `close-merge`.

**Comment by maxnet** [comment]
We moved some files around since you opened the PR.
Translations files are now in src/i18n folder instead of i18n.
As a result of that I could not use the "merge" button in github. And cannot edit the commit through the github webinterface either in that case.

Also your PR was missing adding the _ko file to CMakelists.txt

Was more practical to fix things up with a new commit and close-merge there, than figure out how I could fix up things for the new paths.

**Comment by RuffaloLavoisier** [comment]
@maxnet 
I see , thank you for the explanation.

> (Also your PR was missing adding the _ko file to CMakelists.txt)

My mistake..thanks !

**Pull request closed without merging**
